name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.13.2 # Replace with the version you need

      # 3. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 4. Build TypeScript (optional, if standalone files need compilation)
      # This assumes a `build:ts` script exists in package.json.
      - name: Build TypeScript files
        run: pnpm build:ts
        # If not required, you can remove this step entirely

      # 5. Build Astro project
      - name: Build and upload site
        uses: withastro/action@v3
        with:
          package-manager: pnpm@9.13.2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
